sonar.projectKey=madsfjeldberg_mandatory1
sonar.projectName=mandatory1
sonar.sourceEncoding=UTF-8
sonar.organization=madsfjeldberg
sonar.sources=backend,frontend
sonar.tests=tests
sonar.exclusions=**/node_modules/**,**/playwright-report/**,**/test-results/**
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.spec.ts
